// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6zbkppdVoP1SPEjGK85Zubc7nbg5K0Ns',
    appId: '1:552609060247:web:660ae92950eb2de6ca20d2',
    messagingSenderId: '552609060247',
    projectId: 'mtg-collect-456e5',
    authDomain: 'mtg-collect-456e5.firebaseapp.com',
    storageBucket: 'mtg-collect-456e5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCguAeyjhMDpo4adm5pqzE1Lpt_Tcj29ds',
    appId: '1:552609060247:android:d930631e9ea63c11ca20d2',
    messagingSenderId: '552609060247',
    projectId: 'mtg-collect-456e5',
    storageBucket: 'mtg-collect-456e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKW76rhBTals_GuI4ukHB-5q3tBqPKTxo',
    appId: '1:552609060247:ios:1ee57ac503cc3295ca20d2',
    messagingSenderId: '552609060247',
    projectId: 'mtg-collect-456e5',
    storageBucket: 'mtg-collect-456e5.firebasestorage.app',
    iosBundleId: 'com.example.mtgCollect',
  );
}
